#!/usr/bin/env bash
# db_schema_gen.sh — Generate docs/generated/db-schema.md from schema JSON
# Schema JSON can come from DB MCP queries or be provided directly.
#
# Usage: ralph/db_schema_gen.sh --project-dir DIR --schema-file PATH

set -e

PROJECT_DIR=""
SCHEMA_FILE=""

show_help() {
    cat << 'HELPEOF'
DB Schema Generator — create db-schema.md from schema data

Usage:
    ralph/db_schema_gen.sh --project-dir DIR --schema-file PATH

The schema file should be JSON with this structure:
    {"tables": [{"name": "...", "columns": [{"name": "...", "type": "...", ...}]}]}

Options:
    --project-dir DIR     Project root directory
    --schema-file PATH    Path to schema JSON file (from DB MCP or manual)
    -h, --help            Show this help message
HELPEOF
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        --project-dir)
            PROJECT_DIR="$2"
            shift 2
            ;;
        --schema-file)
            SCHEMA_FILE="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

if [[ -z "$PROJECT_DIR" ]]; then
    echo "Error: --project-dir is required" >&2
    exit 1
fi

if [[ -z "$SCHEMA_FILE" ]]; then
    echo "Error: --schema-file is required" >&2
    exit 1
fi

if [[ ! -f "$SCHEMA_FILE" ]]; then
    echo "Error: schema file not found: $SCHEMA_FILE" >&2
    exit 1
fi

# ─── Generate ─────────────────────────────────────────────────────────────

OUTPUT_FILE="$PROJECT_DIR/docs/generated/db-schema.md"
mkdir -p "$(dirname "$OUTPUT_FILE")"

timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
table_count=$(jq '.tables | length' "$SCHEMA_FILE")

{
    echo "<!-- DO NOT EDIT MANUALLY — generated by db_schema_gen.sh -->"
    echo ""
    echo "# Database Schema"
    echo ""
    echo "**Generated:** $timestamp"
    echo "**Tables:** $table_count"
    echo ""

    for ((i=0; i<table_count; i++)); do
        table_name=$(jq -r ".tables[$i].name" "$SCHEMA_FILE")
        echo "## $table_name"
        echo ""
        echo "| Column | Type | Nullable | Key | References |"
        echo "|--------|------|----------|-----|------------|"

        col_count=$(jq ".tables[$i].columns | length" "$SCHEMA_FILE")
        for ((j=0; j<col_count; j++)); do
            col_name=$(jq -r ".tables[$i].columns[$j].name" "$SCHEMA_FILE")
            col_type=$(jq -r ".tables[$i].columns[$j].type" "$SCHEMA_FILE")
            nullable=$(jq -r ".tables[$i].columns[$j].nullable // true" "$SCHEMA_FILE")
            pk=$(jq -r ".tables[$i].columns[$j].primary_key // false" "$SCHEMA_FILE")
            refs=$(jq -r ".tables[$i].columns[$j].references // \"-\"" "$SCHEMA_FILE")

            nullable_text="YES"
            [[ "$nullable" == "false" ]] && nullable_text="NO"

            key_text="-"
            [[ "$pk" == "true" ]] && key_text="PK"

            echo "| $col_name | $col_type | $nullable_text | $key_text | $refs |"
        done
        echo ""
    done
} > "$OUTPUT_FILE"

echo "[OK] DB schema: $table_count tables → $OUTPUT_FILE"
