#!/usr/bin/env bash
# retro.sh — Sprint Retrospective Report Generator
# Produces docs/quality/retro-report.md with sprint summary, verification
# effectiveness, and documentation health analysis.
# Must complete within 30 seconds (NFR20).
#
# Usage: ralph/retro.sh --project-dir DIR

set -e

PROJECT_DIR=""
GENERATE_COVERAGE=false
GENERATE_FOLLOWUP=false

show_help() {
    cat << 'HELPEOF'
Sprint Retrospective — generate structured retro report

Usage:
    ralph/retro.sh --project-dir DIR

Generates docs/quality/retro-report.md with:
    1. Sprint summary (stories, iterations, duration)
    2. Verification effectiveness (pass rates, iteration counts)
    3. Documentation health (doc-gardener findings)

Options:
    --project-dir DIR   Project root directory
    --coverage          Also generate docs/quality/test-coverage.md
    -h, --help          Show this help message
HELPEOF
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        --project-dir)
            PROJECT_DIR="$2"
            shift 2
            ;;
        --coverage)
            GENERATE_COVERAGE=true
            shift
            ;;
        --followup)
            GENERATE_FOLLOWUP=true
            shift
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

if [[ -z "$PROJECT_DIR" ]]; then
    echo "Error: --project-dir is required" >&2
    exit 1
fi

PROGRESS_FILE="$PROJECT_DIR/ralph/progress.json"
VLOG_FILE="$PROJECT_DIR/ralph/verification-log.json"
OUTPUT_FILE="$PROJECT_DIR/docs/quality/retro-report.md"

mkdir -p "$(dirname "$OUTPUT_FILE")"

timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ─── Gather data ──────────────────────────────────────────────────────────

# Sprint progress
total_stories=0
completed_stories=0
total_iterations=0

if [[ -f "$PROGRESS_FILE" ]]; then
    total_stories=$(jq '.tasks | length' "$PROGRESS_FILE" 2>/dev/null || echo "0")
    completed_stories=$(jq '[.tasks[] | select(.status == "complete")] | length' "$PROGRESS_FILE" 2>/dev/null || echo "0")
    total_iterations=$(jq '[.tasks[].iterations // 0] | add // 0' "$PROGRESS_FILE" 2>/dev/null || echo "0")
fi

avg_iterations="N/A"
if [[ $completed_stories -gt 0 ]]; then
    avg_iterations=$(echo "scale=1; $total_iterations / $completed_stories" | bc 2>/dev/null || echo "$((total_iterations / completed_stories))")
fi

# Verification log
v_total=0
v_pass=0
v_fail=0
pass_rate="N/A"

if [[ -f "$VLOG_FILE" ]]; then
    v_total=$(jq '.events | length' "$VLOG_FILE" 2>/dev/null || echo "0")
    v_pass=$(jq '[.events[] | select(.result == "pass")] | length' "$VLOG_FILE" 2>/dev/null || echo "0")
    v_fail=$(jq '[.events[] | select(.result == "fail")] | length' "$VLOG_FILE" 2>/dev/null || echo "0")
    if [[ $v_total -gt 0 ]]; then
        pass_rate="$((v_pass * 100 / v_total))%"
    fi
fi

# ─── Generate report ──────────────────────────────────────────────────────

{
    echo "<!-- DO NOT EDIT MANUALLY — generated by retro.sh -->"
    echo ""
    echo "# Sprint Retrospective Report"
    echo ""
    echo "**Generated:** $timestamp"
    echo ""

    # ── Sprint Summary ──
    echo "## Sprint Summary"
    echo ""
    echo "| Metric | Value |"
    echo "|--------|-------|"
    echo "| Stories completed | $completed_stories / $total_stories |"
    echo "| Total verification iterations | $total_iterations |"
    echo "| Average iterations per story | $avg_iterations |"
    echo "| Verification checks | $v_total ($v_pass pass, $v_fail fail) |"
    echo "| Pass rate | $pass_rate |"
    echo ""

    # ── Verification Effectiveness ──
    echo "## Verification Effectiveness"
    echo ""

    if [[ -f "$PROGRESS_FILE" ]]; then
        echo "### Per-Story Iteration Counts"
        echo ""
        echo "| Story | Title | Iterations | Status |"
        echo "|-------|-------|------------|--------|"
        jq -r '.tasks[] | "\(.id)\t\(.title)\t\(.iterations // 0)\t\(.status)"' "$PROGRESS_FILE" 2>/dev/null | \
        while IFS=$'\t' read -r id title iters status; do
            echo "| $id | ${title:0:40} | $iters | $status |"
        done
        echo ""
    fi

    if [[ -f "$VLOG_FILE" && $v_fail -gt 0 ]]; then
        echo "### Common Failure Patterns"
        echo ""
        # Count failures per gate count
        jq -r '.events[] | select(.result == "fail") | "gates_passed=\(.gates_passed)/\(.gates_total)"' "$VLOG_FILE" 2>/dev/null | \
            sort | uniq -c | sort -rn | head -5 | while read -r count pattern; do
                echo "- $count occurrences: $pattern"
            done
        echo ""
    fi

    # ── Documentation Health ──
    echo "## Documentation Health"
    echo ""

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    if [[ -f "$SCRIPT_DIR/doc_gardener.sh" ]]; then
        doc_findings=$("$SCRIPT_DIR/doc_gardener.sh" --project-dir "$PROJECT_DIR" --json 2>/dev/null || echo '{"finding_count":0,"findings":[]}')
        doc_count=$(echo "$doc_findings" | jq '.finding_count // 0' 2>/dev/null || echo "0")
        echo "Doc-gardener findings: **$doc_count**"
        echo ""

        if [[ $doc_count -gt 0 ]]; then
            echo "$doc_findings" | jq -r '.findings[] | "- [\(.type)] \(.message)"' 2>/dev/null
            echo ""
        fi
    else
        echo "Doc-gardener not available."
        echo ""
    fi

    # ── Recommendations ──
    echo "## Recommendations"
    echo ""

    if [[ $v_fail -gt 0 ]]; then
        echo "- Review verification failures — $v_fail checks failed"
    fi

    if [[ $total_iterations -gt $((completed_stories * 2)) && $completed_stories -gt 0 ]]; then
        echo "- High iteration count ($avg_iterations avg) — stories may need better AC definition"
    fi

    if [[ $completed_stories -lt $total_stories ]]; then
        remaining=$((total_stories - completed_stories))
        echo "- $remaining stories incomplete — carry forward to next sprint"
    fi

    if [[ $completed_stories -eq $total_stories && $total_stories -gt 0 ]]; then
        echo "- All stories completed — sprint success"
    fi

} > "$OUTPUT_FILE"

# ─── Coverage report ──────────────────────────────────────────────────────

if [[ "$GENERATE_COVERAGE" == "true" ]]; then
    COV_FILE="$PROJECT_DIR/docs/quality/test-coverage.md"
    STATE_FILE="$PROJECT_DIR/.claude/codeharness.local.md"

    # Read baseline and current from state file
    baseline_cov="N/A"
    current_cov="N/A"
    if [[ -f "$STATE_FILE" ]]; then
        baseline_cov=$(grep -o 'baseline: *[0-9]*' "$STATE_FILE" 2>/dev/null | head -1 | awk '{print $2}')
        current_cov=$(grep -o 'current: *[0-9]*' "$STATE_FILE" 2>/dev/null | head -1 | awk '{print $2}')
    fi
    baseline_cov="${baseline_cov:-N/A}"
    current_cov="${current_cov:-N/A}"

    {
        echo "<!-- DO NOT EDIT MANUALLY — generated by retro.sh -->"
        echo ""
        echo "# Test Coverage Report"
        echo ""
        echo "**Generated:** $timestamp"
        echo ""
        echo "## Coverage Summary"
        echo ""
        echo "| Metric | Value |"
        echo "|--------|-------|"
        echo "| Baseline (sprint start) | ${baseline_cov}% |"
        echo "| Final (sprint end) | ${current_cov}% |"

        if [[ "$baseline_cov" != "N/A" && "$current_cov" != "N/A" ]]; then
            delta=$((current_cov - baseline_cov))
            echo "| Delta | +${delta}% |"
        fi

        echo ""
        echo "## Per-Story Coverage Deltas"
        echo ""
        echo "| Story | Title | Before | After | Delta |"
        echo "|-------|-------|--------|-------|-------|"

        if [[ -f "$PROGRESS_FILE" ]]; then
            jq -r '.tasks[] | "\(.id)\t\(.title)\t\(.coverage_delta.before // "N/A")\t\(.coverage_delta.after // "N/A")"' "$PROGRESS_FILE" 2>/dev/null | \
            while IFS=$'\t' read -r id title before after; do
                d=""
                if [[ "$before" != "N/A" && "$after" != "N/A" && "$before" != "null" && "$after" != "null" ]]; then
                    d="+$((after - before))%"
                fi
                echo "| $id | ${title:0:30} | ${before}% | ${after}% | $d |"
            done
        fi
    } > "$COV_FILE"

    echo "[OK] Coverage report generated → $COV_FILE"
fi

# ─── Follow-up story generation ───────────────────────────────────────────

if [[ "$GENERATE_FOLLOWUP" == "true" ]]; then
    FOLLOWUP_FILE="$PROJECT_DIR/docs/quality/retro-followup.md"
    followup_num=0

    {
        echo "# Sprint Retrospective Follow-up Items"
        echo ""
        echo "**Generated:** $timestamp"
        echo ""
        echo "Review and approve items below before adding to next sprint."
        echo ""
        echo "| # | Type | Item | Source |"
        echo "|---|------|------|--------|"

        # Carry-forward: incomplete stories
        if [[ -f "$PROGRESS_FILE" ]]; then
            jq -r '.tasks[] | select(.status != "complete") | "\(.id)\t\(.title)"' "$PROGRESS_FILE" 2>/dev/null | \
            while IFS=$'\t' read -r id title; do
                followup_num=$((followup_num + 1))
                echo "| $followup_num | carry-forward | Story $id: $title (pending/incomplete) | Sprint backlog |"
            done
        fi

        # High-iteration stories: need better AC
        if [[ -f "$PROGRESS_FILE" ]]; then
            jq -r '.tasks[] | select(.iterations > 3) | "\(.id)\t\(.title)\t\(.iterations)"' "$PROGRESS_FILE" 2>/dev/null | \
            while IFS=$'\t' read -r id title iters; do
                followup_num=$((followup_num + 1))
                echo "| $followup_num | story | Refine AC for $id ($title) — took $iters iterations | Retro analysis |"
            done
        fi

        # Verification failures: enforcement gaps
        if [[ -f "$VLOG_FILE" && $v_fail -gt 0 ]]; then
            followup_num=$((followup_num + 1))
            echo "| $followup_num | enforcement | Review $v_fail verification failures — check gate coverage | Verification log |"
        fi

    } > "$FOLLOWUP_FILE"

    echo "[OK] Follow-up items generated → $FOLLOWUP_FILE"
fi

echo "[OK] Retro report generated → $OUTPUT_FILE"
