export function dockerComposeCollectorOnlyTemplate(): string {
  return `# Generated by codeharness — do not edit manually
name: codeharness-collector

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    labels:
      com.codeharness.stack: collector
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    restart: unless-stopped

networks:
  default:
    name: codeharness-collector-net
`;
}

export interface DockerComposeConfig {
  shared: boolean;
}

export function dockerComposeTemplate(config: DockerComposeConfig): string {
  return `# Generated by codeharness — do not edit manually
name: codeharness-shared

services:
  victoria-logs:
    image: victoriametrics/victoria-logs:v1.15.0
    labels:
      com.codeharness.stack: shared
    ports:
      - "9428:9428"
    volumes:
      - victoria-logs-data:/vlogs
    restart: unless-stopped

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.106.1
    labels:
      com.codeharness.stack: shared
    ports:
      - "8428:8428"
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
    restart: unless-stopped

  victoria-traces:
    image: jaegertracing/all-in-one:1.56
    labels:
      com.codeharness.stack: shared
    ports:
      - "14268:14268"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    labels:
      com.codeharness.stack: shared
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    depends_on:
      - victoria-logs
      - victoria-metrics
      - victoria-traces
    restart: unless-stopped

volumes:
  victoria-logs-data:
  victoria-metrics-data:

networks:
  default:
    name: codeharness-shared-net
`;
}
