export interface RemoteOtelConfig {
  logsUrl: string;
  metricsUrl: string;
  tracesUrl: string;
}

export function otelCollectorRemoteTemplate(config: RemoteOtelConfig): string {
  // Strip trailing slashes to avoid double-slash in constructed URLs
  const logsUrl = config.logsUrl.replace(/\/+$/, '');
  const metricsUrl = config.metricsUrl.replace(/\/+$/, '');
  const tracesUrl = config.tracesUrl.replace(/\/+$/, '');

  return `# Generated by codeharness — do not edit manually
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resource/default:
    attributes:
      - key: service.name
        value: "unknown"
        action: insert

exporters:
  otlphttp/logs:
    endpoint: ${logsUrl}/insert/opentelemetry
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: ${metricsUrl}/api/v1/write
    tls:
      insecure: true

  otlp/traces:
    endpoint: ${tracesUrl}
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - resource/default
      exporters:
        - otlphttp/logs
    metrics:
      receivers:
        - otlp
      processors:
        - resource/default
      exporters:
        - prometheusremotewrite
    traces:
      receivers:
        - otlp
      processors:
        - resource/default
      exporters:
        - otlp/traces
`;
}

export function otelCollectorConfigWithCors(): string {
  // Derive from the base template to avoid duplication drift.
  // Inject the CORS block into the HTTP receiver section.
  const base = otelCollectorConfigTemplate();
  const corsBlock = `        cors:
          allowed_origins:
            - "http://localhost:*"
            - "http://127.0.0.1:*"
          allowed_headers:
            - "*"`;

  // Insert CORS after the "endpoint: 0.0.0.0:4318" line in the http receiver
  return base.replace(
    /^(        endpoint: 0\.0\.0\.0:4318)$/m,
    `$1\n${corsBlock}`,
  );
}

export function otelCollectorConfigTemplate(): string {
  return `# Generated by codeharness — do not edit manually
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resource/default:
    attributes:
      - key: service.name
        value: "unknown"
        action: insert

exporters:
  otlphttp/logs:
    endpoint: http://victoria-logs:9428/insert/opentelemetry
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: http://victoria-metrics:8428/api/v1/write
    tls:
      insecure: true

  otlp/traces:
    endpoint: http://victoria-traces:14268
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - resource/default
      exporters:
        - otlphttp/logs
    metrics:
      receivers:
        - otlp
      processors:
        - resource/default
      exporters:
        - prometheusremotewrite
    traces:
      receivers:
        - otlp
      processors:
        - resource/default
      exporters:
        - otlp/traces
`;
}
