/**
 * README.md template for project documentation.
 * Uses static template from templates/docs/readme.md.tmpl with {{VAR}} interpolation.
 *
 * Generated by `codeharness init` when README.md does not exist.
 * Never overwrites an existing README.md.
 */

import { renderTemplateFile } from '../lib/templates.js';

export interface ReadmeTemplateConfig {
  /** Project name (from package.json name or directory basename) */
  projectName: string;
  /** Detected stack: 'nodejs', 'python', 'rust', array of stacks, or null */
  stack: string | string[] | null;
  /** Output of `codeharness --help` for CLI reference section */
  cliHelpOutput: string;
}

/**
 * Generates README.md content from the template config.
 */
export function readmeTemplate(config: ReadmeTemplateConfig): string {
  const { projectName, stack, cliHelpOutput } = config;

  const installCommand = getInstallCommand(stack);

  return renderTemplateFile('templates/docs/readme.md.tmpl', {
    PROJECT_NAME: projectName,
    INSTALL_COMMAND: installCommand,
    CLI_HELP_OUTPUT: cliHelpOutput.trimEnd(),
  });
}

export function getInstallCommand(stack: string | string[] | null): string {
  if (Array.isArray(stack)) {
    const commands = stack.map(s => getSingleInstallCommand(s));
    // Deduplicate in case multiple stacks share an install command
    return [...new Set(commands)].join('\n');
  }
  return getSingleInstallCommand(stack);
}

/** Per-stack install commands, keyed by stack name. */
const INSTALL_COMMANDS: Record<string, string> = {
  python: 'pip install codeharness',
  rust: 'cargo install codeharness',
};

function getSingleInstallCommand(stack: string | null): string {
  if (stack && INSTALL_COMMANDS[stack]) return INSTALL_COMMANDS[stack];
  return 'npm install -g codeharness';
}
