/**
 * README.md template for project documentation.
 * Architecture Decision 6: All templates are TypeScript string literals.
 * Architecture Decision 10: Documentation is load-bearing — wrong docs = verification failure.
 *
 * Generated by `codeharness init` when README.md does not exist.
 * Never overwrites an existing README.md.
 */

export interface ReadmeTemplateConfig {
  /** Project name (from package.json name or directory basename) */
  projectName: string;
  /** Detected stack: 'nodejs', 'python', 'rust', array of stacks, or null */
  stack: string | string[] | null;
  /** Output of `codeharness --help` for CLI reference section */
  cliHelpOutput: string;
}

/**
 * Generates README.md content from the template config.
 */
export function readmeTemplate(config: ReadmeTemplateConfig): string {
  const { projectName, stack, cliHelpOutput } = config;

  const installCommand = getInstallCommand(stack);
  const firstRunCommand = 'codeharness init';
  const exampleUsage = 'codeharness status';

  const lines: string[] = [
    `# ${projectName}`,
    '',
    '## Quick Start',
    '',
    '```bash',
    `# Install`,
    installCommand,
    '',
    '# Initialize the project',
    firstRunCommand,
    '',
    '# Check project status',
    exampleUsage,
    '```',
    '',
    '## Installation',
    '',
    '```bash',
    installCommand,
    '```',
    '',
    '## Usage',
    '',
    `After installation, initialize ${projectName} in your project directory:`,
    '',
    '```bash',
    'codeharness init',
    '```',
    '',
    'This sets up the harness with stack detection, observability, and documentation scaffolding.',
    '',
    '## CLI Reference',
    '',
    '```',
    cliHelpOutput.trimEnd(),
    '```',
    '',
  ];

  return lines.join('\n');
}

export function getInstallCommand(stack: string | string[] | null): string {
  if (Array.isArray(stack)) {
    const commands = stack.map(s => getSingleInstallCommand(s));
    // Deduplicate in case multiple stacks share an install command
    return [...new Set(commands)].join('\n');
  }
  return getSingleInstallCommand(stack);
}

function getSingleInstallCommand(stack: string | null): string {
  if (stack === 'python') return 'pip install codeharness';
  if (stack === 'rust') return 'cargo install codeharness';
  return 'npm install -g codeharness';
}
