/**
 * Dockerfile template for black-box verification environment.
 * Architecture Decision 6: All templates are TypeScript string literals.
 * Architecture Decision 10: Two-layer isolation — Docker container protects host.
 *
 * The image installs the project as a user would (npm install -g from tarball
 * or pip install from dist), includes curl/jq/showboat, and sets OTEL env vars
 * pointing to host.docker.internal:4318.
 *
 * NO source code enters the image — only the built artifact.
 */

export interface VerifyDockerfileConfig {
  /** 'nodejs' or 'python' */
  stack: string;
  /** Tarball filename for Node.js (e.g., "codeharness-0.13.2.tgz") */
  tarballName?: string;
  /** Dist filename for Python (e.g., "mypackage-0.1.0.tar.gz") */
  distFileName?: string;
}

/**
 * Validates that a filename is safe for use in Dockerfile COPY/RUN instructions.
 * Rejects filenames with newlines, shell metacharacters, and path traversal.
 */
function isSafeDockerfileName(name: string): boolean {
  if (!name || name.length > 255) return false;
  // Reject newlines, shell metacharacters, path traversal, and non-printable chars
  if (/[\n\r`$;|&\\><"'{}()\x00-\x1f]/.test(name)) return false;
  if (name.includes('..') || name.includes('/')) return false;
  // Must be a simple filename: alphanumeric, hyphens, underscores, dots
  return /^[a-zA-Z0-9._-]+$/.test(name);
}

/**
 * Generates a Dockerfile for the verification environment.
 * The image:
 * - Installs the project as a user would (npm install -g / pip install)
 * - Includes curl, jq, showboat
 * - Sets OTEL environment variables pointing to host.docker.internal:4318
 * - Contains NO source code
 */
export function verifyDockerfileTemplate(config: VerifyDockerfileConfig): string {
  if (config.stack === 'nodejs') {
    return generateNodeDockerfile(config);
  }
  if (config.stack === 'python') {
    return generatePythonDockerfile(config);
  }
  throw new Error(`Unsupported stack: ${config.stack}`);
}

function generateNodeDockerfile(config: VerifyDockerfileConfig): string {
  const tarball = config.tarballName ?? 'package.tgz';
  if (!isSafeDockerfileName(tarball)) {
    throw new Error(`Unsafe tarball name for Dockerfile: ${tarball}`);
  }
  return `# Generated by codeharness — do not edit manually
# Black-box verification environment (Node.js)
FROM node:20-slim

# Install system utilities
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    jq \\
  && rm -rf /var/lib/apt/lists/*

# Install showboat
RUN npm install -g showboat

# Copy ONLY the built tarball — no source code
COPY ${tarball} /tmp/${tarball}

# Install the project as a user would
RUN npm install -g /tmp/${tarball} && rm /tmp/${tarball}

# OTEL environment variables pointing to host observability stack
ENV OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4318
ENV OTEL_SERVICE_NAME=codeharness-verify
ENV OTEL_TRACES_EXPORTER=otlp
ENV OTEL_METRICS_EXPORTER=otlp
ENV OTEL_LOGS_EXPORTER=otlp

WORKDIR /workspace
`;
}

function generatePythonDockerfile(config: VerifyDockerfileConfig): string {
  const distFile = config.distFileName ?? 'package.tar.gz';
  if (!isSafeDockerfileName(distFile)) {
    throw new Error(`Unsafe dist filename for Dockerfile: ${distFile}`);
  }
  return `# Generated by codeharness — do not edit manually
# Black-box verification environment (Python)
FROM python:3.12-slim

# Install system utilities
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    jq \\
    nodejs \\
    npm \\
  && rm -rf /var/lib/apt/lists/*

# Install showboat
RUN npm install -g showboat

# Copy ONLY the built dist — no source code
COPY ${distFile} /tmp/${distFile}

# Install the project as a user would
RUN pip install --no-cache-dir /tmp/${distFile} && rm /tmp/${distFile}

# OTEL environment variables pointing to host observability stack
ENV OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4318
ENV OTEL_SERVICE_NAME=codeharness-verify
ENV OTEL_TRACES_EXPORTER=otlp
ENV OTEL_METRICS_EXPORTER=otlp
ENV OTEL_LOGS_EXPORTER=otlp

WORKDIR /workspace
`;
}
