import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';
import { info } from '../output.js';
import { readState, writeState, readStateWithBody } from '../state.js';
import type { AppType } from '../stacks/index.js';

export const WEB_OTLP_PACKAGES = [
  '@opentelemetry/sdk-trace-web',
  '@opentelemetry/instrumentation-fetch',
  '@opentelemetry/instrumentation-xml-http-request',
];

export const AGENT_OTLP_PACKAGES_NODE = ['@traceloop/node-server-sdk'];
export const AGENT_OTLP_PACKAGES_PYTHON = ['traceloop-sdk'];

export const NODE_REQUIRE_FLAG = '--require @opentelemetry/auto-instrumentations-node/register';

export function ensureServiceNameEnvVar(projectDir: string, serviceName: string): void {
  const envFilePath = join(projectDir, '.env.codeharness');
  const sanitized = serviceName.replace(/[^a-zA-Z0-9._-]/g, '-');
  const envLine = `OTEL_SERVICE_NAME=${sanitized}`;

  if (existsSync(envFilePath)) {
    const content = readFileSync(envFilePath, 'utf-8');
    const lines = content.split('\n').filter((l, i, arr) => i < arr.length - 1 || l.trim() !== '');
    const idx = lines.findIndex(l => l.startsWith('OTEL_SERVICE_NAME='));
    if (idx !== -1) {
      lines[idx] = envLine;
    } else {
      lines.push(envLine);
    }
    writeFileSync(envFilePath, lines.join('\n') + '\n', 'utf-8');
  } else {
    writeFileSync(envFilePath, envLine + '\n', 'utf-8');
  }
}

export function ensureEndpointEnvVar(projectDir: string, endpoint: string): void {
  const envFilePath = join(projectDir, '.env.codeharness');
  const envLine = `OTEL_EXPORTER_OTLP_ENDPOINT=${endpoint}`;

  if (existsSync(envFilePath)) {
    const content = readFileSync(envFilePath, 'utf-8');
    const lines = content.split('\n').filter((l, i, arr) => i < arr.length - 1 || l.trim() !== '');
    const idx = lines.findIndex(l => l.startsWith('OTEL_EXPORTER_OTLP_ENDPOINT='));
    if (idx !== -1) {
      lines[idx] = envLine;
    } else {
      lines.push(envLine);
    }
    writeFileSync(envFilePath, lines.join('\n') + '\n', 'utf-8');
  } else {
    writeFileSync(envFilePath, envLine + '\n', 'utf-8');
  }
}

export function configureOtlpEnvVars(projectDir: string, stack: string | null, opts?: { endpoint?: string; appType?: AppType }): void {
  const projectName = basename(projectDir);

  const { state, body } = readStateWithBody(projectDir);

  const stackOtlpFields: Record<string, Record<string, string>> = {
    nodejs: { node_require: NODE_REQUIRE_FLAG },
    python: { python_wrapper: 'opentelemetry-instrument' },
    rust: { rust_env_hint: 'OTEL_EXPORTER_OTLP_ENDPOINT' },
  };

  state.otlp = {
    enabled: true,
    endpoint: opts?.endpoint ?? 'http://localhost:4318',
    service_name: projectName,
    mode: state.otlp?.mode ?? 'local-shared',
    ...(stack && stackOtlpFields[stack] ? stackOtlpFields[stack] : {}),
  };

  state.otlp.resource_attributes = 'service.instance.id=$(hostname)-$$';

  writeState(state, projectDir, body);

  ensureServiceNameEnvVar(projectDir, projectName);

  const needsEndpointEnv = new Set(['rust']);
  if (stack && needsEndpointEnv.has(stack)) {
    ensureEndpointEnvVar(projectDir, state.otlp.endpoint);
  }
}

export function configureCli(projectDir: string): void {
  const { state, body } = readStateWithBody(projectDir);

  if (!state.otlp) return;

  state.otlp.cli_env_vars = {
    OTEL_BSP_SCHEDULE_DELAY: '100',
    OTEL_TRACES_SAMPLER: 'always_on',
    OTEL_BLRP_SCHEDULE_DELAY: '100',
  };

  writeState(state, projectDir, body);
}

export function configureWeb(projectDir: string, stack: string | null): void {
  const webInstaller: Record<string, () => void> = {
    nodejs: () => {
      try {
        execFileSync('npm', ['install', ...WEB_OTLP_PACKAGES], { cwd: projectDir, stdio: 'pipe', timeout: 300_000 });
      } catch {
        // Web packages are supplementary; failure is non-fatal
      }
    },
  };
  if (stack && webInstaller[stack]) {
    webInstaller[stack]();
  }

  let endpoint = 'http://localhost:4318';
  try {
    const currentState = readState(projectDir);
    if (currentState.otlp?.endpoint) {
      endpoint = currentState.otlp.endpoint;
    }
  } catch {
    // State not readable — use default endpoint
  }

  const snippet = `// OpenTelemetry Web SDK initialization — generated by codeharness
import { WebTracerProvider } from '@opentelemetry/sdk-trace-web';
import { BatchSpanProcessor } from '@opentelemetry/sdk-trace-base';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { FetchInstrumentation } from '@opentelemetry/instrumentation-fetch';
import { XMLHttpRequestInstrumentation } from '@opentelemetry/instrumentation-xml-http-request';
import { registerInstrumentations } from '@opentelemetry/instrumentation';

const exporter = new OTLPTraceExporter({
  url: '${endpoint}/v1/traces',
});

const provider = new WebTracerProvider();
provider.addSpanProcessor(new BatchSpanProcessor(exporter));
provider.register();

registerInstrumentations({
  instrumentations: [
    new FetchInstrumentation(),
    new XMLHttpRequestInstrumentation(),
  ],
});
`;

  const snippetPath = join(projectDir, 'otel-web-init.js');
  writeFileSync(snippetPath, snippet, 'utf-8');

  const { state, body } = readStateWithBody(projectDir);
  if (state.otlp) {
    state.otlp.web_snippet_path = 'otel-web-init.js';
  }
  writeState(state, projectDir, body);
}

export function configureAgent(projectDir: string, stack: string | null): void {
  const agentInstallers: Record<string, () => boolean> = {
    nodejs: () => {
      try {
        execFileSync('npm', ['install', ...AGENT_OTLP_PACKAGES_NODE], { cwd: projectDir, stdio: 'pipe', timeout: 300_000 });
      } catch {
        // Agent packages are supplementary; failure is non-fatal
      }
      return true;
    },
    python: () => {
      try {
        execFileSync('pip', ['install', ...AGENT_OTLP_PACKAGES_PYTHON], { cwd: projectDir, stdio: 'pipe', timeout: 300_000 });
      } catch {
        try {
          for (const pkg of AGENT_OTLP_PACKAGES_PYTHON) {
            execFileSync('pipx', ['install', pkg], { cwd: projectDir, stdio: 'pipe', timeout: 300_000 });
          }
        } catch {
          // Agent packages are supplementary; failure is non-fatal
        }
      }
      return true;
    },
    rust: () => {
      info('Rust agent SDK not yet supported — skipping agent configuration');
      return false;
    },
  };

  if (stack) {
    const installer = agentInstallers[stack];
    if (installer) {
      const proceed = installer();
      if (!proceed) return;
    }
  }

  const { state, body } = readStateWithBody(projectDir);
  if (state.otlp) {
    state.otlp.agent_sdk = 'traceloop';
  }
  writeState(state, projectDir, body);
}
